### ISSUE TITLE
Update to new Slack API calls

### ISSUE THREAD

**Issue by andreasaez** [orliesaurus/greetingslack#24]
It seems the bot is pointing to the wrong im API call, and the new API call is `conversations`

**Comment by orliesaurus** [comment]
did Slack change their API all of a sudden?

**Comment by andreasaez** [comment]
They have yes, here's the new API calls https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

**Comment by orliesaurus** [comment]
oh 💩

**Comment by andreasaez** [comment]
ha, you're welcome :P

**Comment by orliesaurus** [comment]
Thanks, just one more question - did you try and it doesn't work CURRENTLY...or it will not work...going forward in the future?

**Comment by andreasaez** [comment]
I believe it will continue to work until February of next year when the old API calls will be completely unusable.

**Comment by orliesaurus** [comment]
Thank you very much! Will have to fix it soonish then!

**Comment by yougaindra** [comment]
Old API has already stopped working for newer projects. I got this error when I tried to use old API 
```
{'ok': False, 
'error': 'method_deprecated', '
response_metadata': {'messages': ['[ERROR] This method is retired and can no longer be used. Please use conversations.open instead. Learn more: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api.']}}
```

according to link above
>We'll stop allowing newly created Slack apps to use these deprecated APIs beginning June 10th, 2020.
