### ISSUE TITLE
app failed to create

### ISSUE THREAD

**Issue by stalltron** [orliesaurus/greetingslack#5]
Hi, getting the following error. 
![screen shot 2017-06-23 at 12 40 17 pm](https://user-images.githubusercontent.com/23216491/27491619-2a04dd06-5811-11e7-953a-4c807420f1e1.png)

**Comment by orliesaurus** [comment]
Few days ago Heroku decided to change the default Python or something - i'll add a fix

**Comment by orliesaurus** [comment]
@stalltron done, don't thank me - blame Herokek
