### ISSUE TITLE
Clarify whether the message is private or in #general

### ISSUE THREAD

**Issue by patcon** [orliesaurus/greetingslack#6]
I see usage of the word "broadcast" and things like that, so it's hard to be sure whether this is the sort of thing we're looking for. Even the code uses both "im" and "chat" endpoints, so it's hard to know :)

Can you confirm once and for all that this is a direct message as I suspect, and then I'd be happy to submit a PR clarifying this for the next person who really needs to spelled out explicitly ;)

**Comment by dalbinaco** [comment]
Yes, it is a direct message.

**Comment by orliesaurus** [comment]
If you read the code of the script you would have answered the "issue" yourself, thanks @dalbinaco for jumping in and answering it for me
