### ISSUE TITLE
Send DM when user joins a special debug room

### ISSUE THREAD

**Issue by patcon** [orliesaurus/greetingslack#7]
I saw this in another slackbot. It was a hardcoded room that someone could create on the slack instance for testing, and just archive when done.

Would this be something you'd accept a pull request for?

**Comment by orliesaurus** [comment]
Thanks for suggesting a new feature, I guess you can send a pull request but I am not sure if anyone else would need this feature?

**Comment by orliesaurus** [comment]
I just realised that with this pull request you have not updated requirements.txt since you've added the logging module
